-- ARQUIVO DE SETUP DO BANCO DE DADOS (SUPABASE)
-- Execute este script no SQL Editor do seu Supabase para criar todas as tabelas necessárias.

-- 1. TABELAS DO CRM (Leads e Pipeline)
-- Tabela de Pipeline (Fases da Venda)
CREATE TABLE IF NOT EXISTS pipeline (
  status TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  order_index INT NOT NULL
);

-- Inserir fases padrão
INSERT INTO pipeline (status, label, order_index) VALUES
('new', 'Novo Lead', 1),
('qualified', 'Qualificado', 2),
('negotiation', 'Em Negociação', 3),
('payment_pending', 'Aguardando Pagamento', 4),
('won', 'Venda Realizada', 5),
('lost', 'Perdido', 6)
ON CONFLICT (status) DO NOTHING;

-- Tabela de Leads (Viajantes)
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  phone TEXT UNIQUE NOT NULL,
  name TEXT,
  email TEXT,
  destination_interest TEXT,
  status TEXT REFERENCES pipeline(status) DEFAULT 'new',
  ai_summary TEXT, -- Resumo gerado pela IA
  last_contact TIMESTAMPTZ DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb
);

-- Tabela de Histórico de Mensagens do CRM
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  lead_id UUID REFERENCES leads(id) ON DELETE CASCADE,
  sender TEXT CHECK (sender IN ('user', 'bot', 'human')),
  content TEXT,
  metadata JSONB DEFAULT '{}'::jsonb
);

-- 2. TABELAS DE CONTROLE (Chatbot e Memória)
-- Tabela de Controle de Sessão (Pausa IA / Handoff)
CREATE TABLE IF NOT EXISTS chats (
  phone TEXT PRIMARY KEY,
  ai_service TEXT DEFAULT 'active', -- 'active' ou 'pause'
  email TEXT,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de Memória do LangChain (Postgres Chat Memory)
CREATE TABLE IF NOT EXISTS chat_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id TEXT NOT NULL,
  message JSONB NOT NULL, -- Conteúdo da mensagem em JSON
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_chat_history_session_id ON chat_history(session_id);

-- 3. SEGURANÇA (Row Level Security)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso (Permitir tudo para testes/anonimo - Ajuste conforme necessidade)
DO $$
BEGIN
    -- Policies for leads
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'leads') THEN
        CREATE POLICY "Allow all" ON leads FOR ALL USING (true) WITH CHECK (true);
    END IF;
    
    -- Policies for messages
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'messages') THEN
        CREATE POLICY "Allow all" ON messages FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Policies for pipeline
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'pipeline') THEN
        CREATE POLICY "Allow read" ON pipeline FOR SELECT USING (true);
    END IF;

    -- Policies for chats
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'chats') THEN
        CREATE POLICY "Allow all" ON chats FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- Policies for chat_history
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'chat_history') THEN
        CREATE POLICY "Allow all" ON chat_history FOR ALL USING (true) WITH CHECK (true);
    END IF;
END
$$;

-- FIM DO SCRIPT

-- Tabela de Pacotes de Viagem
CREATE TABLE IF NOT EXISTS public.packages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10,2),
    images TEXT[] DEFAULT '{}',
    videos TEXT[] DEFAULT '{}',
    active BOOLEAN DEFAULT true
);

-- Tabela de Perfis e Cargos (Roles)
CREATE TABLE IF NOT EXISTS public.user_roles (
    id UUID REFERENCES auth.users(id) PRIMARY KEY,
    role TEXT CHECK (role IN ('admin', 'financial', 'agent')) DEFAULT 'agent',
    full_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso (Simplificadas para Teste)
CREATE POLICY "Acesso total a pacotes" ON public.packages FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso total a roles" ON public.user_roles FOR ALL USING (true) WITH CHECK (true);

-- Configuração do Storage (Balde de Mídia)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('package-media', 'package-media', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas de Storage (Acesso Público para Leitura, Autenticado para Escrita)
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Public Access Media') THEN
        CREATE POLICY "Public Access Media" ON storage.objects FOR SELECT USING ( bucket_id = 'package-media' );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Auth Upload Media') THEN
        CREATE POLICY "Auth Upload Media" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'package-media' AND auth.role() = 'authenticated' );
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'objects' AND policyname = 'Auth Delete Media') THEN
        CREATE POLICY "Auth Delete Media" ON storage.objects FOR DELETE USING ( bucket_id = 'package-media' AND auth.role() = 'authenticated' );
    END IF;
END $$;
